# Generated by Django 5.2.13 on 2026-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'permissions': [('ver_proprios_pagamentos', 'Pode ver os próprios pagamentos')], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
