# Generated by Django 5.2.13 on 2026-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('ver_proprio_perfil', 'Pode ver o próprio perfil'), ('editar_proprio_perfil', 'Pode editar o próprio perfil'), ('excluir_propria_conta', 'Pode excluir a própria conta')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
