# Generated by Django 5.2.13 on 2026-09-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_pedido'], 'permissions': [('ver_proprios_pedidos', 'Pode ver os próprios pedidos')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
