# Generated by Django 5.2.13 on 2026-08-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.CharField(choices=[('prata_925', 'Prata 925'), ('prata_950', 'Prata 950'), ('prata_banhada_ouro', 'Prata banhada a ouro'), ('prata_oxidada', 'Prata oxidada')], default='prata_925', max_length=30),
        ),
    ]
